modify the python pinning for the run section
AnacondaRecipes/dropbox-feedstock pull request #17
Opened 2021-12-20 16:42 UTC by varlackc

`dropbox` version `11.25.0`

check the upstream
https://github.com/dropbox/dropbox-sdk-python/tree/v11.25.0

check the pinnings
https://github.com/dropbox/dropbox-sdk-python/blob/main/tox.ini
https://github.com/dropbox/dropbox-sdk-python/blob/main/setup.py
https://github.com/dropbox/dropbox-sdk-python/blob/main/setup.cfg
https://github.com/dropbox/dropbox-sdk-python/blob/main/ez_setup.py

check the changelogs
https://github.com/dropbox/dropbox-sdk-python/blob/v11.25.0/UPGRADING.md

There were no breaking changes mentioned in the documentation

additional research
https://github.com/conda-forge/dropbox-feedstock/issues

There were no open issues in conda forge

verify dev_url
https://github.com/dropbox/dropbox-sdk-python

verify doc_url
https://dropbox-sdk-python.readthedocs.io/en/latest/

pip in the test section

veriy the test section

additional tests

In order to test the dropbox package version 11.25.0 the folowing
command was used:
`conda build dropbox-feedstock --test`
the test result was the following:
`All tests passed`

2021-12-20 16:43 UTC, skupr-anaconda approved these changes

2021-12-20 19:33 UTC, chenghlee requested changes
Further, why is a `run` requirement being duplicated as a `test/requires`?

2021-12-21 15:22 UTC, varlackc commented on recipe/meta.yaml
> -    - stone >=2.*
The unnecessary dependencies were removed form the test section, and the package was tested. 
The package builds properly after removing the unnecessary dependencies.

2021-12-21 18:13 UTC, chenghlee approved these changes

2021-12-21 18:13 UTC, chenghlee commented
Please verify that noarch packages are _actually_ being built.

2021-12-21 21:18 UTC, merged